[project]
name = "computacao-distribuida"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "locust>=2.43.4",
    "matplotlib>=3.10.9",
    "numpy>=2.4.3",
    "pandas>=2.3.3",
    "seaborn>=0.13.2",
    "sns>=0.1",
    "streamlit>=1.55.0",
]
