syntax = "proto3";

package streaming;

// Entidades
message Usuario {
  string id = 1;
  string nome = 2;
  int32 idade = 3;
}

message Musica {
  string id = 1;
  string nome = 2;
  string artista = 3;
}

message Playlist {
  string id = 1;
  string nome = 2;
  string usuario_id = 3;
}

// Mensagens de Requisição e Resposta
message Vazio {}

message IdRequest {
  string id = 1;
}

message ListaUsuariosResponse {
  repeated Usuario usuarios = 1;
}

message ListaMusicasResponse {
  repeated Musica musicas = 1;
}

message ListaPlaylistsResponse {
  repeated Playlist playlists = 1;
}

message CriarUsuarioRequest {
  string nome = 1;
  int32 idade = 2;
}

message CriarMusicaRequest {
  string nome = 1;
  string artista = 2;
}

message CriarPlaylistRequest {
  string nome = 1;
  string usuario_id = 2;
}

message RelacaoPlaylistMusicaRequest {
  string playlist_id = 1;
  string musica_id = 2;
}

// Serviço de Transmissão Remota
service StreamingService {
  rpc ListarUsuarios(Vazio) returns (ListaUsuariosResponse);
  rpc ListarMusicas(Vazio) returns (ListaMusicasResponse);
  rpc ListarPlaylistsPorUsuario(IdRequest) returns (ListaPlaylistsResponse);
  rpc ListarMusicasPorPlaylist(IdRequest) returns (ListaMusicasResponse);
  rpc ListarPlaylistsPorMusica(IdRequest) returns (ListaPlaylistsResponse);
  
  rpc CriarUsuario(CriarUsuarioRequest) returns (Usuario);
  rpc CriarMusica(CriarMusicaRequest) returns (Musica);
  rpc CriarPlaylist(CriarPlaylistRequest) returns (Playlist);
  rpc AdicionarMusicaPlaylist(RelacaoPlaylistMusicaRequest) returns (Playlist);
}