# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import streaming_pb2 as streaming__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in streaming_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class StreamingServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListarUsuarios = channel.unary_unary(
                '/streaming.StreamingService/ListarUsuarios',
                request_serializer=streaming__pb2.Vazio.SerializeToString,
                response_deserializer=streaming__pb2.ListaUsuariosResponse.FromString,
                _registered_method=True)
        self.ListarMusicas = channel.unary_unary(
                '/streaming.StreamingService/ListarMusicas',
                request_serializer=streaming__pb2.Vazio.SerializeToString,
                response_deserializer=streaming__pb2.ListaMusicasResponse.FromString,
                _registered_method=True)
        self.ListarPlaylistsPorUsuario = channel.unary_unary(
                '/streaming.StreamingService/ListarPlaylistsPorUsuario',
                request_serializer=streaming__pb2.IdRequest.SerializeToString,
                response_deserializer=streaming__pb2.ListaPlaylistsResponse.FromString,
                _registered_method=True)
        self.ListarMusicasPorPlaylist = channel.unary_unary(
                '/streaming.StreamingService/ListarMusicasPorPlaylist',
                request_serializer=streaming__pb2.IdRequest.SerializeToString,
                response_deserializer=streaming__pb2.ListaMusicasResponse.FromString,
                _registered_method=True)
        self.ListarPlaylistsPorMusica = channel.unary_unary(
                '/streaming.StreamingService/ListarPlaylistsPorMusica',
                request_serializer=streaming__pb2.IdRequest.SerializeToString,
                response_deserializer=streaming__pb2.ListaPlaylistsResponse.FromString,
                _registered_method=True)
        self.CriarUsuario = channel.unary_unary(
                '/streaming.StreamingService/CriarUsuario',
                request_serializer=streaming__pb2.CriarUsuarioRequest.SerializeToString,
                response_deserializer=streaming__pb2.Usuario.FromString,
                _registered_method=True)
        self.CriarMusica = channel.unary_unary(
                '/streaming.StreamingService/CriarMusica',
                request_serializer=streaming__pb2.CriarMusicaRequest.SerializeToString,
                response_deserializer=streaming__pb2.Musica.FromString,
                _registered_method=True)
        self.CriarPlaylist = channel.unary_unary(
                '/streaming.StreamingService/CriarPlaylist',
                request_serializer=streaming__pb2.CriarPlaylistRequest.SerializeToString,
                response_deserializer=streaming__pb2.Playlist.FromString,
                _registered_method=True)
        self.AdicionarMusicaPlaylist = channel.unary_unary(
                '/streaming.StreamingService/AdicionarMusicaPlaylist',
                request_serializer=streaming__pb2.RelacaoPlaylistMusicaRequest.SerializeToString,
                response_deserializer=streaming__pb2.Playlist.FromString,
                _registered_method=True)


class StreamingServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def ListarUsuarios(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListarMusicas(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListarPlaylistsPorUsuario(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListarMusicasPorPlaylist(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListarPlaylistsPorMusica(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CriarUsuario(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CriarMusica(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CriarPlaylist(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AdicionarMusicaPlaylist(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StreamingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListarUsuarios': grpc.unary_unary_rpc_method_handler(
                    servicer.ListarUsuarios,
                    request_deserializer=streaming__pb2.Vazio.FromString,
                    response_serializer=streaming__pb2.ListaUsuariosResponse.SerializeToString,
            ),
            'ListarMusicas': grpc.unary_unary_rpc_method_handler(
                    servicer.ListarMusicas,
                    request_deserializer=streaming__pb2.Vazio.FromString,
                    response_serializer=streaming__pb2.ListaMusicasResponse.SerializeToString,
            ),
            'ListarPlaylistsPorUsuario': grpc.unary_unary_rpc_method_handler(
                    servicer.ListarPlaylistsPorUsuario,
                    request_deserializer=streaming__pb2.IdRequest.FromString,
                    response_serializer=streaming__pb2.ListaPlaylistsResponse.SerializeToString,
            ),
            'ListarMusicasPorPlaylist': grpc.unary_unary_rpc_method_handler(
                    servicer.ListarMusicasPorPlaylist,
                    request_deserializer=streaming__pb2.IdRequest.FromString,
                    response_serializer=streaming__pb2.ListaMusicasResponse.SerializeToString,
            ),
            'ListarPlaylistsPorMusica': grpc.unary_unary_rpc_method_handler(
                    servicer.ListarPlaylistsPorMusica,
                    request_deserializer=streaming__pb2.IdRequest.FromString,
                    response_serializer=streaming__pb2.ListaPlaylistsResponse.SerializeToString,
            ),
            'CriarUsuario': grpc.unary_unary_rpc_method_handler(
                    servicer.CriarUsuario,
                    request_deserializer=streaming__pb2.CriarUsuarioRequest.FromString,
                    response_serializer=streaming__pb2.Usuario.SerializeToString,
            ),
            'CriarMusica': grpc.unary_unary_rpc_method_handler(
                    servicer.CriarMusica,
                    request_deserializer=streaming__pb2.CriarMusicaRequest.FromString,
                    response_serializer=streaming__pb2.Musica.SerializeToString,
            ),
            'CriarPlaylist': grpc.unary_unary_rpc_method_handler(
                    servicer.CriarPlaylist,
                    request_deserializer=streaming__pb2.CriarPlaylistRequest.FromString,
                    response_serializer=streaming__pb2.Playlist.SerializeToString,
            ),
            'AdicionarMusicaPlaylist': grpc.unary_unary_rpc_method_handler(
                    servicer.AdicionarMusicaPlaylist,
                    request_deserializer=streaming__pb2.RelacaoPlaylistMusicaRequest.FromString,
                    response_serializer=streaming__pb2.Playlist.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'streaming.StreamingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('streaming.StreamingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StreamingService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListarUsuarios(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streaming.StreamingService/ListarUsuarios',
            streaming__pb2.Vazio.SerializeToString,
            streaming__pb2.ListaUsuariosResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListarMusicas(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streaming.StreamingService/ListarMusicas',
            streaming__pb2.Vazio.SerializeToString,
            streaming__pb2.ListaMusicasResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListarPlaylistsPorUsuario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streaming.StreamingService/ListarPlaylistsPorUsuario',
            streaming__pb2.IdRequest.SerializeToString,
            streaming__pb2.ListaPlaylistsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListarMusicasPorPlaylist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streaming.StreamingService/ListarMusicasPorPlaylist',
            streaming__pb2.IdRequest.SerializeToString,
            streaming__pb2.ListaMusicasResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListarPlaylistsPorMusica(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streaming.StreamingService/ListarPlaylistsPorMusica',
            streaming__pb2.IdRequest.SerializeToString,
            streaming__pb2.ListaPlaylistsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CriarUsuario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streaming.StreamingService/CriarUsuario',
            streaming__pb2.CriarUsuarioRequest.SerializeToString,
            streaming__pb2.Usuario.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CriarMusica(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streaming.StreamingService/CriarMusica',
            streaming__pb2.CriarMusicaRequest.SerializeToString,
            streaming__pb2.Musica.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CriarPlaylist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streaming.StreamingService/CriarPlaylist',
            streaming__pb2.CriarPlaylistRequest.SerializeToString,
            streaming__pb2.Playlist.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AdicionarMusicaPlaylist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streaming.StreamingService/AdicionarMusicaPlaylist',
            streaming__pb2.RelacaoPlaylistMusicaRequest.SerializeToString,
            streaming__pb2.Playlist.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
